version: '3'

services:
  luigi:
    build: .
    volumes:
      - ./luigi:/etc/luigi
      - ./luigistate:/luigi/state
      - ./hello_world.py:/etc/luigi/hello_world.py  # Mounting hello_world.py
      - ./tasks:/etc/tasks

    ports:
    - 8082:8082
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: luigi
      POSTGRES_PASSWORD: luigi
      POSTGRES_DB: luigi
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d  # Mount the SQL scripts

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "luigi"]
      interval: 10s
      retries: 5
    restart: always
    networks:
      - backend


networks:
  backend:
volumes:
  postgres-db-volume: